# Generated by Django 6.0.3 on 2026-05-11 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(max_length=65, verbose_name='客户端IP地址')),
                ('method', models.CharField(max_length=10, verbose_name='客户端的请求方法')),
                ('user_name', models.CharField(max_length=65, verbose_name='操作的用户')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='请求操作的时间')),
                ('path', models.CharField(max_length=128, verbose_name='访问路径')),
                ('duration', models.IntegerField(default=0, verbose_name='访问视图函数的耗时，单位毫秒')),
                ('response_type', models.CharField(max_length=65, verbose_name='响应类别')),
                ('status', models.IntegerField(default=200, verbose_name='响应状态码')),
                ('is_success', models.BooleanField(default=False, verbose_name='操作是否成功')),
            ],
            options={
                'verbose_name': '客户端操作记录表',
                'verbose_name_plural': '客户端操作记录表',
                'db_table': 't_operator_log',
            },
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=64, verbose_name='视频标题')),
                ('running_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='播放时长')),
                ('video_file', models.FileField(upload_to='', verbose_name='原始视频文件')),
                ('video_icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='视频预览图片路径')),
                ('running_count', models.IntegerField(default=0, verbose_name='视频播放次数')),
                ('is_success', models.BooleanField(default=False, verbose_name='是否发布成功')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='视频描述')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_list', to=settings.AUTH_USER_MODEL, verbose_name='视频所属用户')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'db_table': 't_videos',
                'ordering': ['id'],
            },
        ),
    ]
