# Generated by Django 6.0.3 on 2026-04-24 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFocusmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='修改时间')),
                ('cur_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_user_list', to=settings.AUTH_USER_MODEL, verbose_name='当前用户')),
                ('focus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_user_list', to=settings.AUTH_USER_MODEL, verbose_name='被关注用户')),
            ],
            options={
                'verbose_name': '用户关注表',
                'verbose_name_plural': '用户关注表',
                'db_table': 'user_focus',
                'ordering': ['id'],
            },
        ),
    ]
